# Generated by Django 4.0.4 on 2022-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=500)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
    ]
