# Generated by Django 4.0.4 on 2022-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pontuacaoquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
