# Generated by Django 4.0.4 on 2022-05-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_pontuacaoquizz_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=150)),
                ('universidade', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('linguagens', models.ManyToManyField(blank=True, to='portfolio.linguagem')),
                ('professor_praticas', models.ManyToManyField(related_name='cadeiras', to='portfolio.professor')),
                ('professor_teoricas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.projeto')),
            ],
        ),
    ]
