# Generated by Django 4.0.4 on 2022-05-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_linguagem_professor_projeto_alter_post_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadeira',
            old_name='professor_praticas',
            new_name='professor_pratica',
        ),
        migrations.RenameField(
            model_name='cadeira',
            old_name='professor_teoricas',
            new_name='professor_teorica',
        ),
    ]
