# Generated by Django 4.0.4 on 2022-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_cadeira_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
    ]
