# Generated by Django 4.0.4 on 2022-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_cadeira_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='anoLetivo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(blank=True),
        ),
    ]
