# Generated by Django 4.0.4 on 2022-05-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_cadeira_anoletivo_alter_cadeira_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='anoLetivo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=0),
        ),
    ]
