# Generated by Django 4.0.4 on 2022-05-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_cadeira_anoletivo_alter_cadeira_ects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='anoLetivo',
        ),
    ]
