# Generated by Django 4.0.4 on 2022-05-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_comentario_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
