# Generated by Django 4.0.4 on 2022-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_cadeira_nome_alter_professor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=80)),
                ('linkin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tfc_terceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.TextField(max_length=50)),
                ('resumo', models.CharField(max_length=1000)),
                ('github_link', models.URLField()),
                ('autores', models.ManyToManyField(related_name='autores', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(related_name='orientadores', to='portfolio.pessoa')),
            ],
        ),
    ]
