# Generated by Django 4.0.4 on 2022-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_pessoa_tfc_terceiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc_terceiros',
            name='resumo',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfc_terceiros',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
