# Generated by Django 4.0.4 on 2022-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_tfc_terceiros_resumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfc_autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=80)),
                ('linkin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tfc_orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=80)),
                ('linkin', models.URLField(blank=True)),
            ],
        ),
    ]
